# Generated by Django 6.0.3 on 2026-03-18 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["name"],
                "verbose_name": "position",
                "verbose_name_plural": "positions",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["deadline"],
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={
                "ordering": ["name"],
                "verbose_name": "task type",
                "verbose_name_plural": "task types",
            },
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "worker", "verbose_name_plural": "workers"},
        ),
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
