# Generated by Django 6.0.3 on 2026-03-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_position_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "position", "verbose_name_plural": "positions"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "task", "verbose_name_plural": "tasks"},
        ),
    ]
