# Generated by Django 6.0.3 on 2026-03-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_position_options_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasktype",
            options={"verbose_name": "task type", "verbose_name_plural": "task types"},
        ),
    ]
