# Generated by Django 6.0.3 on 2026-03-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_tag_task_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
