# Generated by Django 6.0.3 on 2026-03-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_remove_task_tags_delete_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["is_completed", "-deadline"],
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["name"],
                "verbose_name": "team",
                "verbose_name_plural": "teams",
            },
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["username"],
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="project.tasktype",
            ),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_completed"], name="project_tas_is_comp_59d659_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["priority"], name="project_tas_priorit_956ebb_idx"
            ),
        ),
    ]
